elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  index: _book

spring:
  application:
    name: book-search-indexer

server:
  port: 10000

nl:
  endpoint: http://seoji.nl.go.kr/landingPage/SearchApi.do?
  certkey: